spring:
  application:
    name: Auction

  datasource:
    url: jdbc:h2:mem:auctiondb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password: password1234
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: db/changelog/db.changelog-master.yml

  jpa:
    hibernate:
      ddl-auto: none #better validate but I use h2 and have some difference between postgresql
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
